# This is a mapping of Formats to material icons
"Archival Material": "inventory_2"
"Archival Material Manuscript": "history_edu"
"Archive": "inventory_2"
"Art": "image"
"Article": "article"
"Audio": "volume_up"
"Audio (music)": "volume_up"
"Audio (spoken word)": "volume_up"
"Audio CD": "volume_up"
"Audio LP": "volume_up"
"Book": "book"
"Book Chapter": "article"
"Biography": "book"
"Blogs and Blog Posts": "web"
"CDROM": "music_note"
"Conference": "book"
"Conference Proceeding": "article"
"Data File": "draft"
"Database": "draft"
"Dataset": "dataset"
"Dictionaries": "collections_bookmark"
"Directories": "collections_bookmark"
"Dissertation": "book"
"eBook": "book"
"Electronic Resource": "web"
"Encyclopedias": "collections_bookmark"
"Events and Exhibits": "web"
"Government Document": "article"
"Image": "image"
"Images": "photo_library"
"Journal": "collections_bookmark"
"Journal Article": "article"
"Magazine Article": "article"
"Manuscript": "article"
"Map": "map"
"Map-Atlas": "map"
"Microform": "theatres"
"Mixed Material": "filter_none"
"Motion Picture": "theatres"
"Music": "music_note"
"Musical Score": "music_note"
"Newsletter": "article"
"Newspaper": "newspaper"
"Newspaper Article": "article"
"Online Journal": "collections_bookmark"
"Painting": "photo_library"
"Patent": "article"
"Photograph": "photo_library"
"Photographs & Pictorial Works": "photo_library"
"Poem": "article"
"Publication": "article"
"Reference Entry": "article"
"Report": "article"
"Research Guides": "web"
"Review": "reviews"
"Serial": "collections_bookmark"
"Software": "code"
"Staff Directory / People": "web"
"Statistics": "timeline"
"Streaming Audio": "volume_up"
"Streaming Video": "play_circle"
"Text Resource": "article"
"Trade Publication Article": "article"
"Unknown": "unknown_document"
"Video (Blu-ray)": "play_circle"
"Video (DVD)": "play_circle"
"Video (VHS)": "play_circle"
"Video Games": "videogame_asset"
"Video Recording": "play_circle"
"Visual Material": "visibility"
"Web Resource": "web"
"Website": "web"
