# This is the list of libraries
- id: "all"
  name: "All libraries"
- id: "aa"
  name: "U-M Ann Arbor Libraries"
- id: "flint"
  name: "Flint Thompson Library"
- id: "bentley"
  name: "Bentley Historical Library"
- id: "clements"
  name: "William L. Clements Library"
