name: Run Tests
on: push
jobs:
  test-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create .env file
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@d0a56edc74279820eabbe34477511327e710d0de #v2.4.0
      - name: Set up Ruby 4.0
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - name: Install ImageMagick
        uses: mfinelli/setup-imagemagick@7bcb45380be40873a59cc0d4a457ec9228b6c84c # v8.0.0
        with:
          cache: true
      - name: Run linter for Ruby
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Install latest LTS version of Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: lts/*
          check-latest: true
      - name: Clean install
        run: npm ci
      - name: Run tests
        run: npm run test
